# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
r_check_args: '--use-valgrind'
addons:
  apt:
    packages:
      - valgrind
r:
  - oldrel
  - release
  - devel
env:
  - VALGRIND_OPTS='--tool=memcheck --memcheck:leak-check=full --track-origins=yes'


before_install:
  - cd tests
  - R -d "valgrind --tool=memcheck --leak-check=full --track-origins=yes" --vanilla < testthat.R

