# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
r_check_args: '--use-valgrind'
addons:
  apt:
    packages:
      - valgrind
r:
  - oldrel
  - release
  - devel
env:
  - VALGRIND_OPTS='--tool=memcheck --memcheck:leak-check=full --track-origins=yes'


after_success:
  - R CMD build .
  - R -e "install.packages('CamelUp_2.0.1.tar.gz', repos=NULL, type='source')"
  - cd tests
  - R -d "valgrind --tool=memcheck --leak-check=full --track-origins=yes"  --vanilla < testthat.R
  - cd ..

