# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
r_check_args: '--use-valgrind'
addons:
  apt:
    packages:
      - valgrind

r:
  - oldrel
  - release
  - devel
after_success:
  - Rscript -e 'covr::codecov()'
env:
  - VALGRIND_OPTS='--tool=memcheck --memcheck:leak-check=full --track-origins=yes'
