camelScale <- function(){
  colors <- c("darkgreen", "blue", "yellow", "white", "orange")
  values <- c("Green", "Blue", "Yellow", "White", "Orange")
  names(colors) <- values

  return(scale_fill_manual(name = "Color",values = colors))
}

makeBoardGraph <- function(camelDF){
  plt <- camelDF %>%
    ggplot(aes(x = Space, y = Height, fill = Color)) +
    geom_tile(color = "black", size = 1, width = 0.9) +
    ggplot2::coord_cartesian(xlim = c(1, 19), ylim = c(0.5,5.49)) +
    ggplot2::scale_x_continuous(breaks = 1:19) +
    ggplot2::scale_y_continuous(labels = c("0.00", "1.00", "2.00", "3.00", "4.00", "5.00"),
                                breaks = 0:5) +
    theme_classic() +
    camelScale()

  return(plt)
}

makeStackDistGraph <- function(positionDF, color){
  nSims <- nrow(positionDF)/5
  plt <- positionDF %>%
    filter(Color == color) %>%
    group_by(Color, Space, Height) %>%
    summarize(Probability = n()/nSims) %>%
    ggplot(aes(x = Space, y = Height, fill = Color, alpha = Probability)) +
    geom_tile(color = "black", size = 1, width = 0.9) +
    ggplot2::coord_cartesian(xlim = c(1, 19), ylim = c(0.5,5.49)) +
    ggplot2::scale_x_continuous(breaks = 1:19) +
    ggplot2::scale_y_continuous(labels = c("0.00", "1.00", "2.00", "3.00", "4.00", "5.00"),
                                breaks = 0:5) +
    theme_classic() +
    camelScale()
  return(plt)
}

# Run the application

#' Play the game CamelUp
#'
#' @description Run CamelUp in a local web browser. Running locally allows for using the app without an internet connection and running in parallel on the local computer
#' @import ggplot2
#' @import dplyr
#' @import magrittr
#' @return an object representing the CamelUp app as generated by shiny::shinyApp
#' @export
generateUI <- function(){
  ui <- fluidPage(
    titlePanel("Camel Up"),

    sidebarLayout(
      sidebarPanel(
        radioButtons("decisionButtons", "Move Type",
                     c("Move Camel","Place Leg Bet","Place Tile","Place Overall Bet"),
                     selected = "Move Camel"),
        conditionalPanel(condition = "input.decisionButtons == 'Place Leg Bet'",
                         selectInput('legbetcolor',
                                     "Camel Color:",
                                     c("","Yellow","Orange","Blue","Green","White"))
        ),
        conditionalPanel(condition = "input.decisionButtons == 'Place Tile'",
                         selectInput('tiletype',
                                     "Tile Type",
                                     c("","Plus","Minus")),
                         selectInput('tilespace',
                                     "Space Number:",
                                     c("", 1:16))
        ),
        conditionalPanel(condition = "input.decisionButtons == 'Place Overall Bet'",
                         selectInput('overallbettype',
                                     "Bet Type",
                                     c("","Winner", "Loser")),
                         selectInput('overallbetcolor',
                                     "Camel Color:",
                                     c("","Yellow","Orange","Blue","Green","White"))
        ),

        actionButton('submit',
                     "Go!"),
      ),


      mainPanel(
        tabsetPanel(type = "tabs",
                    tabPanel("View Game",
                             plotOutput("gameBoard"),
                             fluidRow(
                               column(width = 4, tableOutput("positionDF")),
                               column(width = 4, tableOutput("legBetDF"))
                             )
                    ),
                    tabPanel("Simulate",
                             fluidRow(
                               column(width = 4, actionButton('copyPlayBoard',
                                                              "Copy Board From Game Play")),
                               column(width = 4, actionButton('copyCustomBoard',
                                                              "Copy Board From Custom Board"))
                             ),
                             radioButtons("simDecision", "Move Type",
                                          c("Move Camel","Place Leg Bet","Place Tile","Place Overall Bet"),
                                          selected = "Move Camel"),
                             conditionalPanel(condition = "input.simDecision == 'Place Leg Bet'",
                                              selectInput('simlegbetcolor',
                                                          "Camel Color:",
                                                          c("","Yellow","Orange","Blue","Green","White"))
                             ),
                             conditionalPanel(condition = "input.simDecision == 'Place Tile'",
                                              selectInput('simtiletype',
                                                          "Tile Type",
                                                          c("","Plus","Minus")),
                                              selectInput('simtilespace',
                                                          "Space Number:",
                                                          c("", 1:16))
                             ),
                             conditionalPanel(condition = "input.simDecision == 'Place Overall Bet'",
                                              selectInput('simoverallbettype',
                                                          "Bet Type",
                                                          c("","Winner", "Loser")),
                                              selectInput('simoverallbetcolor',
                                                          "Camel Color:",
                                                          c("","Yellow","Orange","Blue","Green","White"))
                             ),
                             fluidRow(
                               column(width = 4, numericInput("nSims", "Number of Simulations", value = 1000, min = 100, max = 1000000, step = 100)),
                               column(width = 4, actionButton('simulateGame',
                                                              "Simulate!"))
                             ),
                             selectInput("simColor", "Select Camel of Interest", choices = c("Blue", "White", "Orange", "Yellow", "Green")),


                             plotOutput("boardToSim"),
                             plotOutput("stackDist"),
                             plotOutput("spaceDist")
                    )
        )
      )
    )
  )

  return(ui)

}

# Run the application

#' Play the game CamelUp
#'
#' @description Run CamelUp in a local web browser. Running locally allows for using the app without an internet connection and running in parallel on the local computer
#' @import ggplot2
#' @import dplyr
#' @import magrittr
#' @return an object representing the CamelUp app as generated by shiny::shinyApp
#' @export
server <- function(input, output){
  gamePlay <- Game$new(19, 3, FALSE)
  simBoard <- gamePlay$getBoard()
  simData <- data.frame() #initialize this

  # init
  output$gameBoard <- renderPlot(makeBoardGraph(gamePlay$getCamelDF()))
  output$positionDF <- renderTable(gamePlay$getCamelDF() %>% arrange(-Space, -Height))
  output$legBetDF <- renderTable(gamePlay$getLegBetDF())
  output$boardToSim <- renderPlot(makeBoardGraph(simBoard$getCamelDF()))

  # main panel
  observeEvent(input$submit,{
    if(input$decisionButtons == "Move Camel"){
      gamePlay$takeTurnMove()
    }
    if(input$decisionButtons == "Place Leg Bet"){
      gamePlay$takeTurnLegBet(input$legbetcolor)
    }
    if(input$decisionButtons == "Place Tile"){
      gamePlay$takeTurnPlaceTile(as.numeric(input$tilespace), input$tiletype == "Plus")
    }
    if(input$decisionButtons == "Place Overall Bet"){
      if(input$overallbettype == "Winner"){
        gamePlay$takeTurnPlaceOverallWinner(input$overallbetcolor)
      }
      if(input$overallbettype == "Loser"){
        gamePlay$takeTurnPlaceOverallLoser(input$overallbetcolor)
      }
    }

    output$gameBoard <- renderPlot(makeBoardGraph(gamePlay$getCamelDF()))
    output$positionDF <- renderTable(gamePlay$getCamelDF() %>% arrange(-Space, -Height))
    output$legBetDF <- renderTable(gamePlay$getLegBetDF())

  })


  # sim panel
  observeEvent(input$copyPlayBoard, {
    simBoard <- gamePlay$getBoard()
    output$boardToSim <- renderPlot(makeBoardGraph(simBoard$getCamelDF()))
  })

  observeEvent(input$simulateGame, {
    simObj <- Simulator$new(simBoard)
    simData <- simObj$simulateDecision(input$simDecision %in% c("Move Camel", "Place Leg Bet", "Place Tile"), input$nSims)
    positionDF <- simData$position
    rankingDF <- simData$ranking
    output$stackDist <- renderPlot(makeStackDistGraph(positionDF, input$simColor))
  })

}

# Run the application

#' Play the game CamelUp
#'
#' @description Run CamelUp in a local web browser. Running locally allows for using the app without an internet connection and running in parallel on the local computer
#' @import ggplot2
#' @import dplyr
#' @import magrittr
#' @import shiny
#' @return an object representing the CamelUp app as generated by shiny::shinyApp
#' @export
playCamelUp <- function(){
  shiny::shinyApp(ui = generateUI(), server = server)
}
